# .golangci-lint.yaml
run:
  deadline: 5m
  tests: true

# linters-settings:
#   errcheck:
#     # ファイルや任意のパッケージの関数のチェックを除外することができる。
#     # https://github.com/kisielk/errcheck#excluding-functions
#     # exclude: /path/to/file.txt

linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - misspell
    - errcheck
    - staticcheck
    - prealloc
    - ineffassign
