version: '3.1'

services:
  redis:
    image: redis:6.2.1
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /home/ubuntu/elasticsearch-data:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.1
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    links:
      - redis
networks:
  default:
    external: true
    name: monolithic_network
